apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: {{ .Values.image_name }}
        imagePullPolicy: Always
        name: springboot
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: hello-world
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-app
  type: NodePort
