apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-app
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: web-app
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: springboot
        image: {{ .Values.image_name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
